// deno-lint-ignore-file no-explicit-any
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import QRCode from "npm:qrcode@1.5.4";
import { guard } from "../_shared/auth.ts";
import { admin } from "../_shared/db.ts";
import { toCamel } from "../_shared/case.ts";
import { json, preflight, subPath } from "../_shared/http.ts";

/**
 * /functions/v1/qr
 *   GET ?all=true       every table with its QR (qr.manage)
 *   GET ?tableId=<id>   one table with its QR (qr.manage)
 *
 * The QR encodes `<origin>/?view=public-menu&table=<qr_token>` — the diner
 * scans it, the app calls POST /table-session with that token to open a
 * session. The token itself is generated by the database, never here.
 */

Deno.serve(async (req: Request) => {
  const pf = preflight(req);
  if (pf) return pf;
  if (req.method !== "GET") return json(req, { error: "Method not allowed" }, 405);

  const g = await guard(req, { permission: "qr.manage" });
  if (!g.ok) return g.response;
  const tenantId = g.session.tenantId;

  const url = new URL(req.url);
  const segments = subPath(req, "qr");
  const tableId = segments[0] ?? url.searchParams.get("tableId");
  const all = url.searchParams.get("all") === "true";

  // Where the QR should point. SITE_URL is the canonical deployment origin;
  // fall back to the caller's own origin so local development works untouched.
  const origin =
    Deno.env.get("SITE_URL") ?? req.headers.get("origin") ?? url.origin;

  const db = admin();

  const render = async (table: any) => {
    const targetUrl = `${origin}/?view=public-menu&table=${table.qr_token}`;
    const qrData = await QRCode.toDataURL(targetUrl, {
      margin: 1,
      width: 400,
      color: { dark: "#161922", light: "#ffffff" },
    });
    return { ...toCamel(table), qrUrl: targetUrl, qrData };
  };

  try {
    if (all) {
      const { data, error } = await db
        .from("tables")
        .select("*")
        .eq("tenant_id", tenantId)
        .order("name", { ascending: true });
      if (error) return json(req, { error: error.message }, 500);
      return json(req, await Promise.all((data ?? []).map(render)));
    }

    if (!tableId) return json(req, { error: "tableId or all=true required" }, 400);

    const { data: table, error } = await db
      .from("tables")
      .select("*")
      .eq("id", tableId)
      .eq("tenant_id", tenantId) // tenant scoping
      .maybeSingle();
    if (error) return json(req, { error: error.message }, 500);
    if (!table) return json(req, { error: "Table not found" }, 404);

    const { qrData, ...rest } = await render(table);
    const wide = await QRCode.toDataURL(rest.qrUrl, {
      margin: 1,
      width: 512,
      color: { dark: "#161922", light: "#ffffff" },
    });
    return json(req, { table: toCamel(table), qrUrl: rest.qrUrl, qrData: wide, qrDataSmall: qrData });
  } catch (err) {
    return json(req, { error: (err as Error).message ?? "Unexpected error" }, 500);
  }
});
